config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'
  devise_for :users
  root to: "tops#index"
  resources :tops, only: [:index, :show]
  resources :posts do 
    collection do
      get 'search'
    end
    resources :comments, only: [:create]
  end
  resources :cooks do 
    resource :favorites, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resources :reviews
  end
  resources :blogs
  resources :incomes, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :getmoneys, only: [:new, :create, :edit, :update, :destroy]
end

app/models/blog.rb
class Blog < ApplicationRecord

  belongs_to :user

  with_options presence: true do
    validates :title
    validates :start_time
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_blog, only: [:edit, :update, :destroy, :show]
  before_action :not_user_do, only: [:edit, :update, :destroy, :show]

  def index
    @blogs = Blog.all
    @blog = Blog.new
  end

  def new
    @blog = Blog.new
  end

  def show
  end

  def create
    @blog = Blog.new(blog_parameter)
    if @blog.valid?
      @blog.save
      flash[:notice] = '予定を登録しました'
      redirect_to blogs_path
    else
      render "new"
    end
  end


  

  def destroy
    @blog.destroy
    flash[:notice] = '予定を削除しました'
    redirect_to blogs_path
  end

  def edit
  end

  def update
    if @blog.update(blog_parameter)
      flash[:notice] = '予定を変更しました'
      redirect_to blogs_path
    else
      render 'edit'
    end
  end

  private


  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time).merge(user_id: current_user.id)
  end



  def not_user_do
    unless current_user.id == @blog.user_id
      redirect_to blogs_path
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<div class='form-header'>
  <h1 class="form-header-text">予定登録</h1>
</div>

<%= form_with(model: @blog, local: true) do |form| %>

  <div class="form-group-time">
    <span class="time">時間</span><%= form.datetime_select :start_time %>
  </div>


  <div class="form-group">
    <div class="form-tag">タイトル</div>
    <%= form.text_field :title %>
  </div>


  <div class="form-group">
    <div class="form-tag">内容</div>
    <%= form.text_area :content %>
  </div>

  

 <div class="cook-send">
    <%= form.submit "Send", class:"register-red-btn" %>
 </div>
<% end %>

app/views/blogs/index.html.erb
<%= render "shared/header" %>

<div class="header">
  <div class="inner-header">
    <h1 class="title">
        カレンダー
    </h1>
    <li class='new-post'>
      <%= link_to "予定登録", new_blog_path, class:"post-btn"%>
    </li>
  </div>
</div>

<div class="row">
  <div class="schedule">
    <div class="schedule-title">予定一覧</div>
      <table class="schedule-table">
        <thead class="schedule-thead">
          <tr>
            <th>タイトル</th>
            <th>日程</th>
          </tr>
        </thead>
        <tbody class="schedule-tbody">
        <% @blogs.each do |blog| %>
          <% if user_signed_in? && current_user.id == blog.user_id %>
            <tr>
              <td><%= link_to blog.title, blog_path(blog.id)%></td>
              <td><%= blog.start_time.strftime("%m-%d") %></td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
    </div>




    <br>
    <div class="col-md-8">
      <%= month_calendar events: @blogs do |date, blogs| %>
        <%= date.day %>
        
        <% blogs.each do |blog| %>
          <% if user_signed_in? && current_user.id == blog.user_id %>
            <div>
              <%= link_to blog.title, blog_path(blog.id) %>
            </div>
          <% end %>
        <% end %>

      <% end %>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<div class='form-header'>
  <h1 class="form-header-text">予定登録</h1>
</div>

<%= form_with(model: @blog, local: true) do |form| %>

  <div class="form-group-time">
    <span class="time">時間</span><%= form.datetime_select :start_time %>
  </div>


  <div class="form-group">
    <div class="form-tag">タイトル</div>
    <%= form.text_field :title %>
  </div>


  <div class="form-group">
    <div class="form-tag">内容</div>
    <%= form.text_area :content %>
  </div>

  

 <div class="cook-send">
    <%= form.submit "Send", class:"register-red-btn" %>
 </div>
<% end %>

app/views/blogs/show.html.erb
<div class="blog-show">
  <div class="blog-show-inner">
    <p>
      <strong>タイトル</strong>
      <%= @blog.title %>
    </p>

    <p>
      <strong>内容</strong>
      <%= @blog.content %>
    </p>

    <p>
      <strong>日時</strong>
      <%= @blog.start_time.strftime("%m-%d") %>
    </p>

    <%= link_to '編集', edit_blog_path(@blog) %>
    <%= link_to '消去',blog_path(@blog.id), method: :delete, data: { confirm: '削除しますか？' } %>
    <%= link_to '戻る', blogs_path %>
  </div>
</div>