config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'
  devise_for :users
  root to: "tops#index"
  resources :tops, only: [:index, :show]
  resources :posts do 
    collection do
      get 'search'
    end
    resources :comments, only: [:create]
  end
  resources :cooks do 
    resource :favorites, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resources :reviews
  end
  resources :blogs
  resources :incomes, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :getmoneys, only: [:new, :create, :edit, :update, :destroy]
end

app/models/cook.rb
class Cook < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :reviews, dependent: :destroy

  
  with_options presence: true do
    validates :name, length: {maximum: 30}
  end
  validates :description, length: {maximum: 140}
  validates :point, length: {maximum: 50}
  validates :appearance,
            :numericality => {
              :only_interger => true,
              :greater_than_or_equal_to => 1,
              :less_than_or_equal_to => 5
            },
            allow_nil: true



  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else 
      0.0
    end
  end

  def avg_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else 
      0.0
    end
  end

end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_cook, only: [:edit, :update, :destroy, :show]
  def index
    @cooks = Cook.includes(:user).order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @cook = Cook.new
  end

  def create
    @cook = Cook.new(cook_params)
    if @cook.valid?
      @cook.save
      flash[:notice] = '投稿が完了しました'
      return redirect_to cooks_path
    else
      render "new"
    end
  
  end


  def show
    @review = Review.new
  end


  def edit
  end

  def update
    if @cook.update(cook_params)
      flash[:notice] = '投稿を編集しました'
      redirect_to cook_path(@cook)
    else 
      render "edit"
    end
  end

  def destroy
    if @cook.destroy
      flash[:notice] = '投稿を削除しました'
      redirect_to cooks_path
    end
  end






  private
  def cook_params
    params.require(:cook).permit(:name, :description, :portion, :point, :reference, :time, :appearance, :memo, :image).merge(user_id: current_user.id)
  end


  def set_cook
    @cook = Cook.find(params[:id])
  end
  
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/views/cooks/edit.html.erb
<div class="container">
  <div class='form-header'>
    <h1 class="form-header-text">料理登録</h1>
  </div>
  <div class="row">
    <div class="#">
      <%= form_with model: @cook, local: true do |f| %>
        <%#= render 'shared/error_messages', object: f.object %>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <div class="new-message-field">
              <p>クリックして料理の写真をアップロード※必須</p>
              <%= f.file_field :image, id:"new-item-image", class: 'form-control' %>
            </div>
          </div>
        </div>
        
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">料理名</label>
            <span class="indispensable">※必須</span>
          </div>
          <%= f.text_field :name, class: 'form-control', id: 'dish_name' %>
        </div>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">説明</label>
            <span class="input-unneed">※任意</span>
          </div>
          <%= f.text_field :description, size: "60x4", class: 'form-control', id: 'dish_description' %>
        </div>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">分量</label>
            <span class="input-unneed">※任意</span>
          </div>
          <%= f.text_field :portion, class: 'form-control', id: 'dish_portion' %>
        </div>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">ポイント</label>
            <span class="input-unneed">※任意</span>
          </div>
          <%= f.text_field :point, size: "30x4", class: 'form-control', id: 'dish_tips' %>
        </div>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">参照サイト</label>
            <span class="input-unneed">※任意</span>
          </div>
          <%= f.text_field :reference, class: 'form-control', id: 'dish_reference' %>
        </div>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">所要時間</label>
            <span class="input-unneed">※任意</span>
          </div>
          <%= f.text_field :time, class: 'form-control', id: 'dish_required_time' %>
        </div>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">見た目</label>
            <span class="input-unneed">※任意</span>
          </div>
          <%= f.text_field :appearance, class: 'form-control', id: 'dish_popularity' %>
        </div>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">メモ</label>
            <span class="input-unneed">※任意</span>
          </div>
          <%= f.text_field :memo, class: 'form-control', id: 'dish_cook_memo' %>
        </div>

        <div class='cook-send'>
          <%= f.submit "送信" ,class:"register-red-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cooks/index.html.erb
  <%= render "shared/header" %>
  <div class="header">
    <div class="inner-header">
      <h1 class="title">
        本日の料理
      </h1>
      <li class='new-post'>
        <%= link_to "料理投稿", new_cook_path, class:"post-btn"%>
      </li>
    </div>
  </div>




  <div class="cook">
    <% @cooks.each do |cook| %>
    <div>
      <ul class="cooks">
        <li class="cook-li-image">
          <span> 
            <%= image_tag cook.image.variant(resize: '150x150'),  class: 'mesage-image' if cook.image.attached? %>
          </span>
        </li>
        <li>
          <span class="cook-name"><%= link_to cook.name, cook_path(cook.id) %></span>
          <% if current_user.already_liked?(cook)%>
            <%= link_to cook_likes_path(cook), method: :delete do %>
              <i class="fas fa-heart"></i>
            <% end %>
          <% else %>
            <%= link_to cook_likes_path(cook), method: :post do %>
              <i class="far fa-heart"></i>
            <% end %>
          <% end %>
          <br>
          <span class="cook-time">所要時間：<%= cook.time %>分</span>
          <span class="appearance">人気度：<%= cook.appearance %></span><br>
          <span class="reference"><%= link_to "作り方", cook_path(cook.id) %></span><br>
          <span class="cook-created-at">投稿日時: <%=cook.created_at%><span>
        </li>
      <ul>
      </div>
    <% end %>
    <%= paginate @cooks %>

  </div>




<%#= render "shared/footer" %>

app/views/cooks/new.html.erb
<div class="container">
  <div class='form-header'>
    <h1 class="form-header-text">料理登録</h1>
  </div>
  <div class="row">
    <div class="#">
      <%= form_with model: @cook, local: true do |f| %>
        <%#= render 'shared/error_messages', object: f.object %>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <div class="new-message-field">
              <p>クリックして料理の写真をアップロード※必須</p>
              <%= f.file_field :image, id:"new-item-image", class: 'form-control' %>
            </div>
          </div>
        </div>
        
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">料理名</label>
            <span class="indispensable">※必須</span>
          </div>
          <%= f.text_field :name, class: 'form-control', id: 'dish_name' %>
        </div>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">説明</label>
            <span class="input-unneed">※任意</span>
          </div>
          <%= f.text_field :description, size: "60x4", class: 'form-control', id: 'dish_description' %>
        </div>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">分量</label>
            <span class="input-unneed">※任意</span>
          </div>
          <%= f.text_field :portion, class: 'form-control', id: 'dish_portion' %>
        </div>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">ポイント</label>
            <span class="input-unneed">※任意</span>
          </div>
          <%= f.text_field :point, size: "30x4", class: 'form-control', id: 'dish_tips' %>
        </div>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">参照サイト</label>
            <span class="input-unneed">※任意</span>
          </div>
          <%= f.text_field :reference, class: 'form-control', id: 'dish_reference' %>
        </div>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">所要時間</label>
            <span class="input-unneed">※任意</span>
          </div>
          <%= f.text_field :time, class: 'form-control', id: 'dish_required_time' %>
        </div>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">見た目</label>
            <span class="input-unneed">※任意</span>
          </div>
          <%= f.text_field :appearance, class: 'form-control', id: 'dish_popularity' %>
        </div>
        <div class = 'form-group'>
          <div class='form-text-wrap'>
            <label class="form-text">メモ</label>
            <span class="input-unneed">※任意</span>
          </div>
          <%= f.text_field :memo, class: 'form-control', id: 'dish_cook_memo' %>
        </div>

        <div class='cook-send'>
          <%= f.submit "送信" ,class:"register-red-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cooks/show.html.erb
<%= render "shared/header" %>


<div class="show-header">
  <div class="show-inner-header">
    <h1 class="show-title">
      今日の食卓
    </h1>
  </div>
</div>

<div class="show">

  <div class="show-cook-inner">
    <div class="show-inner-title">
      <ul class="show-inner-like">
        <li><h1><%= @cook.name %></h1></li>
        <li>
          <% if current_user.already_liked?(@cook)%>
            <%= link_to cook_likes_path(@cook), method: :delete do %>
              <i class="fas fa-heart"></i>
            <% end %>
          <% else %>
            <%= link_to cook_likes_path(@cook), method: :post do %>
              <i class="far fa-heart"></i>
            <% end %>
          <% end %>
        </li>
        
          <li><p><%= @cook.likes.count %></p></li>
      </ul>
      
      <% if user_signed_in? %>
        <%= render 'users/favorite_form' %> 
      <% end %>
    </div>
    <div class="show-image">
      <%= image_tag @cook.image.variant(resize: '250x250'), class: 'mesage-image' if @cook.image.attached? %>
    </div>
    <% if @cook.description.present? %>
      <h2><%= @cook.description %></h2>
    <% end %>
    <% if @cook.reference.present? %>
      <h2 class="cook-reference">作り方：<%= link_to "#{@cook.reference}", @cook.reference, target: "_blank" %></h2>
    <% end %>
    <% if @cook.portion.present? %>
      <h2 class="cook-portion">分量：<span class="cook-other-info"><%= @cook.portion %></span> 人分</h2>

    <% end %>
    <% if @cook.point.present? %>
      <div class="cook-point">
        <h2 class="cook-title-point">コツ・ポイント</h2>
        <h2><%= @cook.point %></h2>
      </div>
    <% end %>

    <div class="show-cook-other-info">
      <% if @cook.time.present? %>
        <div class="cook-info">
          <h2>所要時間：<span class="cook-other-info"><%= @cook.time %></span>分</span></h2>
        </div>
      <% end %>
      <% if @cook.appearance.present? %>
        <div class="cook-info">
          <h2>見た目：<span class="cook-other-info"><%= @cook.appearance %><span></h2>
        </div>
      <% end %>

      <div class="review"> 
        <%= render 'reviews/form', review: @review, cook: @cook %>
      </div>

      
      <div class="show-new-post">
        <div class="show-post-sub">
          
          <%= link_to "一覧ページへ", cooks_path, class:"show-post"%>
        </div>
      </div>
    </div>


  </div>

  <div class="show-sub">
    <div class="show-new-post">
        <p class="show-cook-text">自分レシピを紹介しよう！</p>
        <div class="show-post-sub">
          <%= link_to "料理投稿", new_cook_path, class:"show-post"%>
        </div>
    </div>
  
  
    <% if user_signed_in? && current_user.id == @cook.user_id %>
      <div class="show-edit-delete">
        <ul>
          <li class="show-post-sub-edit"><%= link_to "編集", edit_cook_path(@cook.id), class:"show-post-edit"%></li>
          <li class="show-post-sub-delete"><%= link_to "削除", cook_path(@cook.id), method: :delete, class:"show-post-delete"%></li>
          <li class="show-post-sub-fav"><%= link_to "お気に入り", top_path(@cook.id), class:"show-post-fav"%></li>
        </ul>
      </div>
    <% elsif user_signed_in? %>
      <div class="show-fav">
        <ul>
          <li style="text-align:center;"><p>お気に入り登録一覧！！</p></li>
          <li class="show-post-sub-fav"><%= link_to "お気に入り", top_path(@cook.id), class:"show-post-fav"%></li>
        </ul>
      </div>
    <% end %>
  </div>

</div>






<%= render "shared/footer" %>