config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'
  devise_for :users
  root to: "tops#index"
  resources :tops, only: [:index, :show]
  resources :posts do 
    collection do
      get 'search'
    end
    resources :comments, only: [:create]
  end
  resources :cooks do 
    resource :favorites, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resources :reviews
  end
  resources :blogs
  resources :incomes, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :getmoneys, only: [:new, :create, :edit, :update, :destroy]
end

app/models/getmoney.rb
class Getmoney < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category2
  belongs_to :user


  with_options presence: true do
    validates :amount
    validates :start_time
  end
  validates :category2_id, numericality: { other_than: 1 }
end

app/controllers/getmoneys_controller.rb
class GetmoneysController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_getmoney, only: [:edit, :update, :destroy]
  before_action :not_user_do_getmoney, only: [:edit, :update, :destroy]


  def new
    @getmoney = Getmoney.new
  end

  def create
    @getmoney = Getmoney.new(getmoney_params)
    if @getmoney.save
      flash[:notice] = '収入を登録しました'
      redirect_to incomes_path
    else 
      render :new
    end
  end

  def edit
  end

  def update
    if @getmoney.update(getmoney_params)
      flash[:notice] = '家計簿を編集しました'
      redirect_to incomes_path
    else 
      render "edit"
    end
  end


  def destroy
    @getmoney.destroy
    flash[:notice] = '収入を削除しました'
    redirect_to incomes_path
  end


  private
  def getmoney_params
    params.require(:getmoney).permit(:amount, :memo, :category2_id, :start_time).merge(user_id: current_user.id)
  end

  def set_getmoney
    @getmoney = Getmoney.find(params[:id])
  end

  def not_user_do_getmoney
    unless current_user.id == @getmoney.user_id
      redirect_to incomes_path
    end
  end
end

app/helpers/getmoneys_helper.rb
module GetmoneysHelper
end

app/views/getmoneys/edit.html.erb
<div class='form-header'>
  <h1 class="form-header-text">収入登録</h1>
</div>

<%= form_with(model: @getmoney, local: true) do |form| %>

  <div class="form-group-time">
    <span class="time">日付</span><%= form.datetime_select :start_time %>
  </div>


  <div class="form-group">
    <div class="form-tag">金額</div>
    <%= form.text_field :amount %>
  </div>

  
  <div class="form-group">
    <div class="form-tag">メモ</div>
    <%= form.text_area :memo %>
  </div>

  <div class="form-group">
    <div class="form-tag">カテゴリー</div>
    <%= form.collection_select(:category2_id, Category2.all, :id, :name, {}, {class:"genre-select"}) %>
  </div>

  

 <div class="cook-send">
    <%= form.submit "Send", class:"register-red-btn" %>
 </div>
<% end %>

<div class="delete-income">
  <%= link_to 'この収支を削除',getmoney_path(@getmoney.id), method: :delete, data: { confirm: '削除しますか？' }, class:"delete-link" %>
</div>

app/views/getmoneys/new.html.erb
<div class='form-header'>
  <h1 class="form-header-text">収入登録</h1>
</div>

<%= form_with(model: @getmoney, local: true) do |form| %>

  <div class="form-group-time">
    <span class="time">日付</span><%= form.datetime_select :start_time %>
  </div>


  <div class="form-group">
    <div class="form-tag">金額</div>
    <%= form.text_field :amount %>
  </div>

  
  <div class="form-group">
    <div class="form-tag">メモ</div>
    <%= form.text_area :memo %>
  </div>

  <div class="form-group">
    <div class="form-tag">カテゴリー</div>
    <%= form.collection_select(:category2_id, Category2.all, :id, :name, {}, {class:"genre-select"}) %>
  </div>

 <div class="cook-send">
    <%= form.submit "Send", class:"register-red-btn" %>
 </div>
<% end %>

<p class=''>
  <%= link_to "支出登録", new_income_path, class:""%>
</p>