config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'
  devise_for :users
  root to: "tops#index"
  resources :tops, only: [:index, :show]
  resources :posts do 
    collection do
      get 'search'
    end
    resources :comments, only: [:create]
  end
  resources :cooks do 
    resource :favorites, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resources :reviews
  end
  resources :blogs
  resources :incomes, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :getmoneys, only: [:new, :create, :edit, :update, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  has_many :comments, dependent: :destroy
  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations
  has_one_attached :image

  
  # with_options presence: true do
  #   validates :title
  #   validates :text
  # end

  # #ジャンルの選択が「--」の時は保存できないようにする
  # validates :genre_id, numericality: { other_than: 1 } 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search, :show]
  before_action :search_post, only: [:index, :search]
  
  
  
  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(5)
    set_post_column
  end

  def search
    @results = @p.result.all

    if params[:keyword] == ""
      tag = Tag.where(['name LIKE ?', "%#{params[:keyword]}%"] )
      render json:{ keyword: tag }
    end
  end

  def new
    @post = PostsTag.new
  end

  def create
    @post = PostsTag.new(post_params)
    tag_list = params[:post][:name].split(',')
    if @post.valid?
      @post.save(tag_list)
      flash[:notice] = '投稿が完了しました'
      return redirect_to posts_path
    else
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      flash[:notice] = '投稿を削除しました'
      redirect_to posts_path
    end
  end

  def edit
    @post = Post.find(params[:id])
    @form = PostsTag.new(post: @post)
  end

  def update
    @post = Post.find(params[:id])
    @form = PostsTag.new(post_params, post: @post)
    tag_list = params[:post][:name].split(",")
    if @form.valid?
      @form.save(tag_list)
      flash[:notice] = '投稿を編集しました'
      return redirect_to post_path(@post)
    else
      render :edit
    end

  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :genre_id, :image, :name).merge(user_id: current_user.id)
  end


  def search_post
    @p = Post.ransack(params[:q])
  end


  def set_post_column
    @post_title = Post.select("genre_id").distinct 
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
  <div class='form-header'>
    <h1 class="form-header-text">New Post</h1>
  </div>

<%= form_with model: @post, url: post_path, local: true do |f| %>


  <div class='new-message-form'>


    <div class="form-group">
      <%= f.label :title,  "タイトル" %>
      <%= f.text_field :title, class:"input-message" %>
    </div>

    <div class="form-group">
      <%= f.label :title,  "ジャンル" %>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
    </div>

    <div class="form-group">
      <%= f.label :text,  "テキスト" %>
      <%= f.text_area :text, class:"new-input-message" %>
    </div>

    <div class="form-group">
      <p>
        クリックしてファイルをアップロード※任意
      </p>
      <%= f.file_field :image, id:"new-item-image" %>
    </div>


    <div class="form-group", id='tag-field'>
      <%= f.label :name, "タグ" %>
      <%= f.text_field :name, class:"new-input-tag" %>
    </div>


    <div id="search-result">
    </div>


  </div>


  <div class="cook-send">
    <%= f.submit "Send", class:"register-red-btn" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<%= render "shared/header" %>
<div class="header">
  <div class="inner-header">
    <h1 class="title">
     掲示板
    </h1>
    <li class='new-post'>
      <%= link_to "New Post", new_post_path, class:"post-btn"%>
    </li>
  </div>
</div>

<div class="message">

<div class="message-wrap">

  <%= search_form_for @p, url: search_posts_path do |f| %>
    <ul class="search-post">
      <li class="search-li-name">
        <span><%= f.label :genre_id_eq, 'ジャンル名' %></span>
        <%= f.collection_select :genre_id_eq, Genre.all, :id, :name, {} %>
      </li>
      <li class="search-li-submit">
        <%= f.submit '検索' %>
      </li>
    </ul>
  <% end %>

  

  


    <% @posts.each do |post|%>
      <div class="post">
        <%= link_to post_path(post.id) do %>
          <div class="post-date">
            投稿日時：<%= post.created_at %>
          </div>
          <div class="post-content">
            <%= post.title %>
          </div>
        <% end %>
      </div>
    <%end%>
    <%= paginate @posts %>
  </div>
</div>

<%#= render "shared/footer" %>

app/views/posts/new.html.erb
  <div class='form-header'>
    <h1 class="form-header-text">New Post</h1>
  </div>

<%= form_with model: @post, url: posts_path, local: true do |f| %>


  <div class='new-message-form'>


    <div class="form-group">
      <%= f.label :title,  "タイトル(※必須)" %>
      <%= f.text_field :title, class:"input-message" %>
    </div>

    <div class="form-group">
      <%= f.label :title,  "ジャンル(※必須)" %>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
    </div>

    <div class="form-group">
      <%= f.label :text,  "テキスト(※必須)" %>
      <%= f.text_area :text, class:"new-input-message" %>
    </div>

    <div class="form-group">
      <p>
        クリックしてファイルをアップロード(※任意)
      </p>
      <%= f.file_field :image, id:"new-item-image" %>
    </div>


    <div class="form-group", id='tag-field'>
      <%= f.label :name, "タグ(※任意)" %>
      <%= f.text_field :name, placeholder:"例) #主婦,#味方", class:"new-input-tag" %>
    </div>

    <div id="search-result"></div>




  </div>


  <div class="cook-send">
    <%= f.submit "Send", class:"register-red-btn" %>
  </div>
<% end %>

app/views/posts/search.html.erb
<%= render "shared/header" %>
<div class="header">
  <div class="inner-header">
    <h1 class="title">
     検索結果
    </h1>
    <li class='new-post'>
      <%= link_to "New Post", new_post_path, class:"post-btn"%>
    </li>
  </div>
</div>


<div class="message-wrap">
  <%# 検索結果の個数で条件分岐 %>
  <% if @results.length !=0 %>
    <% @results.each do |result| %>
    <div class="post">
      <%= link_to post_path(result.id) do %>
        <div class="post-date">
          投稿日時：<%= result.created_at %>
        </div>
        <div class="post-content">
          <%= result.title %>
        </div>
      <% end %>
    </div>
    <% end %>
  <% else %>
    <p class="search-no-response">該当する投稿はありません</p>
  <% end %>
  <br>
  <div class="back-search-btn">
    <%= link_to '一覧ページへ戻る', posts_path%>
  </div>
</div>

app/views/posts/show.html.erb
<% if @post.present? %>

  <%= render "shared/header" %>


  <div class="show-header">
    <div class="show-inner-header">
      <h1 class="show-title">
        主婦の掲示板
      </h1>
    </div>
  </div>

  <div class="show">

    <div class="show-inner">
      <div class="show-inner-title">
        <h1><%= @post.title %></h1>
      </div>
      <div class="show-main">
        <ul class="show-genre">
          <li class="show-genre-title">ジャンル -<li>
          <li><%= @post.genre.name%></li>
        </ul>
        <p class="show-text"><%= @post.text %></p>
        <div class="show-image">
          <%= image_tag @post.image.variant(resize: '150x150'), class: 'mesage-image' if @post.image.attached? %>
        </div>
        <div class="show-tag">
          <%@post.tags.each do |tag| %>
            <%=tag.name%>
          <%end%>
        </div>
      </div>

      <%# コメント投稿 %>
      <div class="comment">
        <h4 class="show-comments-title">＜コメント一覧＞</h4>
        <div class="show-comments">
          <% @comments.each do |comment| %>
            <div class="show-comment-content">
              <p>
                <strong><%=comment.user.nickname%>：</strong>
                <%= comment.text %>
              </p>
            </div>
          <% end %>
        </div>

        <div class="show-container">
          <% if user_signed_in? %>
            <%= form_with(model: [@post, @comment], local: true, id: "comment-form") do |form| %>
              <%= form.text_field :text, placeholder: "コメントする", rows: "2" %>
              <%= form.submit "SEND", id: "post-comment-submit" %>
            <% end %>
          <% else %>
            <strong><p style="font-size:12px;">※※※ コメントの投稿には<%= link_to '新規登録', new_user_registration_path, class: "sign-up" %>/<%= link_to 'ログイン', new_user_session_path, class: "login" %>が必要です ※※※</p></strong>
          <% end %>
        </div>
      </div>


    </div>
    <div class="show-sub">
      <div class="show-new-post">
          <p>悩み相談や雑談など何でもOK！</p>
          <div class="show-post-sub">
            <%= link_to "New Post", new_post_path, class:"show-post"%>
          </div>
      </div>


      <% if user_signed_in? && current_user.id == @post.user_id %>
        <div class="show-edit-delete">
          <ul>
            <li class="show-post-sub-edit"><%= link_to "編集", edit_post_path(@post.id), class:"show-post-edit"%></li>
            <li class="show-post-sub-delete"><%= link_to "削除", post_path(@post.id), method: :delete, class:"show-post-delete"%></li>
          </ul>
        </div>
      <% end %>



    </div>
    
  </div>
<% end %>





<%= render "shared/footer" %>